def stringfunc(s):
    le=len(s)
    u=s.upper()
    l=s.lower()
    c=s.capitalize()
    t=s.title()
    iu=s.isupper()
    il=s.islower()
    ia=s.isalpha()
    id=s.isdigit()
    ial=s.isalnum()
    print("Length of given string is:",le)
    print("Upper of given string is:",u)    
    print("Lower of given string is:",l)    
    print("capitalize of given string is:",c)    
    print("Title of given string is:",t)    
    print("Given string isupper:",iu)    
    print("Given string islower:",il)    
    print("Given string isalpha:",ia)    
    print("Given string isdigit:",id)    
    print("Given string isalnum:",ial)    
